// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOhWxKzrfolrNmLDpHU9Z9ibdrP2BElYY',
    appId: '1:993947725622:web:236596fc6b7339202c0d97',
    messagingSenderId: '993947725622',
    projectId: 'ecommerce-ddc9b',
    authDomain: 'ecommerce-ddc9b.firebaseapp.com',
    storageBucket: 'ecommerce-ddc9b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrsiSxsdrtAXrHcunMh3bY0sgwNVWIe_c',
    appId: '1:993947725622:android:55fa2dfde608f82a2c0d97',
    messagingSenderId: '993947725622',
    projectId: 'ecommerce-ddc9b',
    storageBucket: 'ecommerce-ddc9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa-2VPOW1IVg6JuJNwmcHuJAX9PHoKmrk',
    appId: '1:993947725622:ios:b4d32c99db38895c2c0d97',
    messagingSenderId: '993947725622',
    projectId: 'ecommerce-ddc9b',
    storageBucket: 'ecommerce-ddc9b.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa-2VPOW1IVg6JuJNwmcHuJAX9PHoKmrk',
    appId: '1:993947725622:ios:b4d32c99db38895c2c0d97',
    messagingSenderId: '993947725622',
    projectId: 'ecommerce-ddc9b',
    storageBucket: 'ecommerce-ddc9b.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOhWxKzrfolrNmLDpHU9Z9ibdrP2BElYY',
    appId: '1:993947725622:web:6c2a6dfaa6a95c012c0d97',
    messagingSenderId: '993947725622',
    projectId: 'ecommerce-ddc9b',
    authDomain: 'ecommerce-ddc9b.firebaseapp.com',
    storageBucket: 'ecommerce-ddc9b.firebasestorage.app',
  );
}
